runtime: python311  # Specifies the runtime for the app

entrypoint: gunicorn -b :$PORT main:app  # The entry point to run the app using Gunicorn

env_variables:
  DB_USER: "root"  # Set environment variable for DB user
  DB_PASSWORD: "khushi123&"  # Set environment variable for DB password
  DB_NAME: "exam_form"  # Set environment variable for DB name
  DB_CONNECTION_NAME: "examform:asia-south1:exam_db"  # Cloud SQL connection name

handlers:
- url: /static
  static_dir: static  # Serve static files from the 'static' directory

- url: /.*
  script: auto  # Automatic script routing for the app

cloud_sql_instances: "examform:asia-south1:exam_db"  # Reference to your Cloud SQL instance

automatic_scaling:
  max_instances: 1  # Set max instances for automatic scaling
