runtime: python311
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_USER: "root"
  DB_PASSWORD: "khushi123&"
  DB_NAME: "exam_form"
  DB_CONNECTION_NAME: "examform:asia-south1:exam_db"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

cloud_sql_instances: "examform:asia-south1:exam_db" 
