runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_USER: root
  DB_PASS: khushi123&
  DB_NAME: examform
  DB_CONNECTION_NAME: examform:asia-south1:exam_db

beta_settings:
  cloud_sql_instances: examform:asia-south1:exam_db



